---
title: WCA
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Inteligência em comércio exterior.
baseurl: 
url: http://wca.com.br
markdown: kramdown
sass:
  style: compressed
