---
title: WCA
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections (página inicial)
    output: false
  servicos:
    title: Serviços
    output: true
    permalink: "/servicos/:path/"
  uploads:
    title: Uploads
    output: true
  utilidades:
    title: Utilidades
    output: true
    permalink: "/utilidades/:path/"
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: servicos
  values:
    layout: page
- scope:
    path: ''
    type: utilidades
  values:
    layout: page
description: Inteligência em comércio exterior.
baseurl: ''
url: http://wca.com.br
markdown: kramdown
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
