---
title: WCA
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  servicos:
    title: Serviços
    output: true
    permalink: "/servicos/:path/"
  uploads:
    title: Uploads
    output: true
  utilidades:
    title: Utilidades
    output: true
    permalink: "/utilidades/:path/"
  icones:
    title: icones
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: 
- scope:
    path: ''
    type: pages
  values:
    excerpt: 
- scope:
    path: ''
    type: servicos
  values:
    layout: servico
    excerpt: 
    image: 
    ordem: 
- scope:
    path: ''
    type: utilidades
  values:
    layout: utilidade
    icone: 
    cor: 
tagline: Inteligência em comércio exterior
description: Inteligência em comércio exterior
baseurl: 
url: http://wca.com.br
markdown: kramdown
sass:
  style: compressed
  selo image: "/uploads/WCA%20Logo30anos.jpg"
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
plugins:
- jekyll-sitemap
long-title: WCA Consultoria e Comércio Exterior Ltda.
endereco: Rua Barão de Teffé, 1000 – Conjunto 161 – 16° andar – Jardim Ana Maria
localidade: CEP 13208-761 | Jundiaí - SP | Brasil
telefones:
- numero: "+551121368484"
  rotulo: "+55 (11) 2136-8484"
  icone: telefone
email: wca@wca.com.br
google-fonts: 
base-font-family: Frutiger, Calibri, sans-serif
title-font-family: Frutiger, Calibri, sans-serif
servicos-image: "/uploads/SERVICOS_2_.jpg"
utilidades-image: "/uploads/UTILIDADES_.jpg"
