---
title: WCA
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections (não alterar)
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: Inteligência em comércio exterior.
baseurl: ''
url: http://wca.com.br
markdown: kramdown
sass:
  style: compressed
exclude:
  - node_modules
  - desktop.ini
  - gulpfile.js
  - npm-debug.log
