---
title: WCA
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  servicos:
    title: Serviços
    output: true
    permalink: "/servicos/:path/"
  uploads:
    title: Uploads
    output: true
  utilidades:
    title: Utilidades
    output: true
    permalink: "/utilidades/:path/"
  icones:
    title: icones
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: 
- scope:
    path: ''
    type: servicos
  values:
    layout: page
    image: 
- scope:
    path: ''
    type: utilidades
  values:
    layout: utilidade
    icone: 
tagline: Inteligência em comércio exterior
description: Inteligência em comércio exterior
baseurl: 
url: http://wca.com.br
markdown: kramdown
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
long-title: WCA Consultoria e Comércio Exterior Ltda.
endereco: Av. Antonio Segre, 141
localidade: CEP 13201-843 | Jundiaí - SP | Brasil
telefones:
- numero: "+551121368484"
  rotulo: "+55 (11) 2136-8484"
- numero: "+551121368483"
  rotulo: "+55 (11) 2136-8483"
email: wca@wca.com.br
google-fonts: <link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed"
  rel="stylesheet">
base-font-family: Georgia, serif
title-font-family: "'Barlow Semi Condensed', sans-serif"
servicos-image: "/uploads/servi%C3%A7os2.jpg"
utilidades-image: "/uploads/utilidades.jpg"
